In [24]:
!pip install sentence-transformers pandas numpy scikit-learn

Requirement already satisfied: sentence-transformers in .\venv\Lib\site-packages (5.3.0)
Requirement already satisfied: pandas in .\venv\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy in .\venv\Lib\site-packages (2.4.2)
Requirement already satisfied: scikit-learn in .\venv\Lib\site-packages (1.8.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in .\venv\Lib\site-packages (from sentence-transformers) (5.3.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in .\venv\Lib\site-packages (from sentence-transformers) (1.7.1)
Requirement already satisfied: torch>=1.11.0 in .\venv\Lib\site-packages (from sentence-transformers) (2.10.0)
Requirement already satisfied: scipy in .\venv\Lib\site-packages (from sentence-transformers) (1.17.1)
Requirement already satisfied: typing_extensions>=4.5.0 in .\venv\Lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in .\venv\Lib\site-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: packaging>=20.0 in .\venv\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in .\venv\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in .\venv\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.2.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in .\venv\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer in .\venv\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in .\venv\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in .\venv\Lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in .\venv\Lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in .\venv\Lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in .\venv\Lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: anyio in .\venv\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.12.1)
Requirement already satisfied: certifi in .\venv\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in .\venv\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in .\venv\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in .\venv\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in .\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\venv\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: joblib>=1.3.0 in .\venv\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in .\venv\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in .\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: sympy>=1.13.3 in .\venv\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in .\venv\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in .\venv\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: setuptools in .\venv\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (82.0.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in .\venv\Lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: colorama in .\venv\Lib\site-packages (from tqdm->sentence-transformers) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in .\venv\Lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in .\venv\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in .\venv\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in .\venv\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in .\venv\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in .\venv\Lib\site-packages (from rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in .\venv\Lib\site-packages (from rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in .\venv\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)

In [25]:
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances, manhattan_distances

In [26]:
df = pd.read_csv("cleaned_transcripts.csv")

print("Dataset loaded successfully")
print("Shape:", df.shape)

df.head()

Dataset loaded successfully
Shape: (398, 4)

,video_id,title,datetime,transcript
0,E-CH3-VyVck,Why is Git INSANELY Fast? (And How Commits Ac...,2026-02-24 11:00:29+00:00,You have typed get commit thousands of times. ...
1,URI5GsOBznk,YouTube Recommendation Engine: Complete Meltdo...,2026-02-21 04:26:16+00:00,"YouTube went down. [music] 350,000 users repor..."
2,8d2eG7bdepQ,Implementing OAuth and MFA: Full Authenticatio...,2026-02-18 11:00:16+00:00,Every time you click sign in with Google or co...
3,GQ6piqfwr5c,"How Stripe Built AI Agents That Write 1,000+ P...",2026-02-14 13:02:10+00:00,Scribe just revealed something big. They have ...
4,p5hA8rpCRXw,The Selenium Problem: Why QA Teams Waste 40% o...,2026-02-11 11:01:25+00:00,Here's a stat that surprised me. QA team spend...

In [27]:
model_name = "all-MiniLM-L6-v2"
model = SentenceTransformer(model_name)

print("Loaded model:", model_name)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 9544.72it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loaded model: all-MiniLM-L6-v2

In [28]:
model_name = "all-MiniLM-L6-v2"
model = SentenceTransformer(model_name)

print("Loaded model:", model_name)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 11385.85it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loaded model: all-MiniLM-L6-v2

In [29]:
titles = df["title"].fillna("").astype(str).tolist()
transcripts = df["transcript"].fillna("").astype(str).tolist()

title_embeddings = model.encode(titles, show_progress_bar=True)
transcript_embeddings = model.encode(transcripts, show_progress_bar=True)

print("Title embeddings shape:", title_embeddings.shape)
print("Transcript embeddings shape:", transcript_embeddings.shape)

Batches: 100%|██████████| 13/13 [00:00<00:00, 17.98it/s]
Batches: 100%|██████████| 13/13 [00:09<00:00,  1.43it/s]

Title embeddings shape: (398, 384)
Transcript embeddings shape: (398, 384)

In [30]:
def compute_scores(query_embedding, metric_name="cosine"):
    query_embedding = query_embedding.reshape(1, -1)

    if metric_name == "cosine":
        title_scores = cosine_similarity(query_embedding, title_embeddings)[0]
        transcript_scores = cosine_similarity(query_embedding, transcript_embeddings)[0]

    elif metric_name == "euclidean":
        title_scores = -euclidean_distances(query_embedding, title_embeddings)[0]
        transcript_scores = -euclidean_distances(query_embedding, transcript_embeddings)[0]

    elif metric_name == "manhattan":
        title_scores = -manhattan_distances(query_embedding, title_embeddings)[0]
        transcript_scores = -manhattan_distances(query_embedding, transcript_embeddings)[0]

    else:
        raise ValueError("Unsupported metric")

    return title_scores, transcript_scores

In [31]:
def returnSearchResults(
    query,
    df,
    metric_name="cosine",
    top_k=5,
    threshold=0.5,
    title_weight=0.3,
    transcript_weight=0.7
):
    # Step 1: encode query
    query_embedding = model.encode([query])[0]

    # Step 2: compute title and transcript scores
    title_scores, transcript_scores = compute_scores(query_embedding, metric_name)

    # Step 3: combine scores
    final_scores = (title_weight * title_scores) + (transcript_weight * transcript_scores)

    # Step 4: attach scores to dataframe
    results_df = df.copy()
    results_df["title_score"] = title_scores
    results_df["transcript_score"] = transcript_scores
    results_df["final_score"] = final_scores

    # Step 5: apply threshold
    filtered_df = results_df[results_df["final_score"] >= threshold]

    # Step 6: sort and get top-k
    filtered_df = filtered_df.sort_values(by="final_score", ascending=False).head(top_k)

    return filtered_df[["video_id", "title", "datetime", "final_score"]]

In [32]:
df = pd.read_csv("cleaned_transcripts.csv")

query = "What is ai agent?"

results = returnSearchResults(
    query=query,
    df=df,
    metric_name="cosine",
    top_k=5,
    threshold=0.5,
    title_weight=0.3,
    transcript_weight=0.7
)

results

,video_id,title,datetime,final_score
83,Jj1-zb38Yfw,Agentic AI Explained So Anyone Can Get It!,2025-06-18 10:00:35+00:00,0.764929
106,MWv33xofJ40,AI Assistant vs AI Agent 🤖 | What&39;s the Dif...,2025-04-25 12:30:21+00:00,0.709019
102,9UNPwGRNo_k,I Tested DeepAgent: How AI Agents Use MCP to T...,2025-04-30 10:00:27+00:00,0.672424
17,voSYs_XDsog,I Built a Game Without Writing Code (AI Agent ...,2025-12-10 12:02:04+00:00,0.630302
220,SYHqSAWQ4NY,"Autonomous AI Agents, Large Action Model and M...",2024-11-22 18:02:34+00:00,0.618158

In [33]:
query = "What is ai agent?"

for metric in ["cosine", "euclidean", "manhattan"]:
    print(f"\nMetric: {metric}")
    display(returnSearchResults(
        query=query,
        df=df,
        metric_name=metric,
        top_k=5,
        threshold=0.5,
        title_weight=0.3,
        transcript_weight=0.7
    ))

Metric: cosine

,video_id,title,datetime,final_score
83,Jj1-zb38Yfw,Agentic AI Explained So Anyone Can Get It!,2025-06-18 10:00:35+00:00,0.764929
106,MWv33xofJ40,AI Assistant vs AI Agent 🤖 | What&39;s the Dif...,2025-04-25 12:30:21+00:00,0.709019
102,9UNPwGRNo_k,I Tested DeepAgent: How AI Agents Use MCP to T...,2025-04-30 10:00:27+00:00,0.672424
17,voSYs_XDsog,I Built a Game Without Writing Code (AI Agent ...,2025-12-10 12:02:04+00:00,0.630302
220,SYHqSAWQ4NY,"Autonomous AI Agents, Large Action Model and M...",2024-11-22 18:02:34+00:00,0.618158

Metric: euclidean

Empty DataFrame
Columns: [video_id, title, datetime, final_score]
Index: []

Metric: manhattan

Empty DataFrame
Columns: [video_id, title, datetime, final_score]
Index: []

In [34]:
query = "What is ai agent?"

for threshold in [0.3, 0.5, 0.7]:
    print(f"\nThreshold: {threshold}")
    display(returnSearchResults(
        query=query,
        df=df,
        metric_name="cosine",
        top_k=5,
        threshold=threshold,
        title_weight=0.3,
        transcript_weight=0.7
    ))

Threshold: 0.3

,video_id,title,datetime,final_score
83,Jj1-zb38Yfw,Agentic AI Explained So Anyone Can Get It!,2025-06-18 10:00:35+00:00,0.764929
106,MWv33xofJ40,AI Assistant vs AI Agent 🤖 | What&39;s the Dif...,2025-04-25 12:30:21+00:00,0.709019
102,9UNPwGRNo_k,I Tested DeepAgent: How AI Agents Use MCP to T...,2025-04-30 10:00:27+00:00,0.672424
17,voSYs_XDsog,I Built a Game Without Writing Code (AI Agent ...,2025-12-10 12:02:04+00:00,0.630302
220,SYHqSAWQ4NY,"Autonomous AI Agents, Large Action Model and M...",2024-11-22 18:02:34+00:00,0.618158

Threshold: 0.5

,video_id,title,datetime,final_score
83,Jj1-zb38Yfw,Agentic AI Explained So Anyone Can Get It!,2025-06-18 10:00:35+00:00,0.764929
106,MWv33xofJ40,AI Assistant vs AI Agent 🤖 | What&39;s the Dif...,2025-04-25 12:30:21+00:00,0.709019
102,9UNPwGRNo_k,I Tested DeepAgent: How AI Agents Use MCP to T...,2025-04-30 10:00:27+00:00,0.672424
17,voSYs_XDsog,I Built a Game Without Writing Code (AI Agent ...,2025-12-10 12:02:04+00:00,0.630302
220,SYHqSAWQ4NY,"Autonomous AI Agents, Large Action Model and M...",2024-11-22 18:02:34+00:00,0.618158

Threshold: 0.7

,video_id,title,datetime,final_score
83,Jj1-zb38Yfw,Agentic AI Explained So Anyone Can Get It!,2025-06-18 10:00:35+00:00,0.764929
106,MWv33xofJ40,AI Assistant vs AI Agent 🤖 | What&39;s the Dif...,2025-04-25 12:30:21+00:00,0.709019

In [35]:
queries_df = pd.read_csv("query_video_mapping.csv")
queries_df.head()

                              query relevant_video_id
0         What is diagram visually?       67Ekk-rM5dE
1           Explain performance dns       xv0Be4QfkH0
2      Explain benchmarks dragonfly       j1PkkSddZcE
3  How does processing stream work?       mG3xQb_-rV4
4      How does sql injection work?       WUBWIVCJLHI

In [36]:
evaluation_results = []

for _, row in queries_df.iterrows():
    query = row["query"]
    expected_video = row["relevant_video_id"]

    results = returnSearchResults(
        query=query,
        df=df,
        metric_name="cosine",
        top_k=5,
        threshold=0.5,
        title_weight=0.3,
        transcript_weight=0.7
    )

    retrieved_ids = results["video_id"].tolist()

    if expected_video in retrieved_ids:
        rank = retrieved_ids.index(expected_video) + 1
    else:
        rank = None

    evaluation_results.append({
        "Query": query,
        "Expected Video": expected_video,
        "Retrieved Rank": rank
    })

eval_df = pd.DataFrame(evaluation_results)
eval_df.head(10)

                                 Query Expected Video  Retrieved Rank
0            What is diagram visually?    67Ekk-rM5dE             NaN
1              Explain performance dns    xv0Be4QfkH0             NaN
2         Explain benchmarks dragonfly    j1PkkSddZcE             1.0
3     How does processing stream work?    mG3xQb_-rV4             1.0
4         How does sql injection work?    WUBWIVCJLHI             1.0
5        What is architecture sidecar?    FMxUYhYDiys             1.0
6                 What is apis harder?    qnXTTmPPiz0             1.0
7  How does advantages fusionaut work?    t3HvCLYnrRY             NaN
8         Explain legacy microservices    DpuQ3-7e-rY             2.0
9             What is structured apps?    t-tTh94NI78             NaN

In [37]:
valid_ranks = eval_df["Retrieved Rank"].dropna()

top1_recall = (valid_ranks <= 1).mean()
top3_recall = (valid_ranks <= 3).mean()
top5_recall = (valid_ranks <= 5).mean()
avg_rank = valid_ranks.mean()

summary_df = pd.DataFrame([{
    "Top-1 Recall": round(top1_recall, 3),
    "Top-3 Recall": round(top3_recall, 3),
    "Top-5 Recall": round(top5_recall, 3),
    "Avg Rank": round(avg_rank, 2)
}])

summary_df

   Top-1 Recall  Top-3 Recall  Top-5 Recall  Avg Rank
0         0.803           1.0           1.0      1.27

In [38]:
eval_df.to_csv("module7_evaluation_output.csv", index=False)
summary_df.to_csv("module7_summary.csv", index=False)

print("Module 7 outputs saved")

Module 7 outputs saved